"""Added all fields to model and removed image_path

Revision ID: 9ca0f818e005
Revises: a0d861fce4d3
Create Date: 2023-12-07 02:10:00.291636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca0f818e005'
down_revision = 'a0d861fce4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vertical', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('horizontal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('firstfacelocation', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('secondfacelocation', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('rotationvalue', sa.Integer(), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('rotationvalue')
        batch_op.drop_column('secondfacelocation')
        batch_op.drop_column('firstfacelocation')
        batch_op.drop_column('horizontal')
        batch_op.drop_column('vertical')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vertical', sa.INTEGER(), nullable=False),
    sa.Column('horizontal', sa.INTEGER(), nullable=False),
    sa.Column('firstfacelocation', sa.VARCHAR(length=120), nullable=False),
    sa.Column('secondfacelocation', sa.VARCHAR(length=120), nullable=False),
    sa.Column('rotationvalue', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('imagecategory', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
