"""add name and unique constraints to data field

Revision ID: a0d861fce4d3
Revises: 4c2fbc9753cf
Create Date: 2023-11-15 19:22:01.267500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d861fce4d3'
down_revision = '4c2fbc9753cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_entry', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('image_unique', ['data'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack_entry', schema=None) as batch_op:
        batch_op.drop_constraint('image_unique', type_='unique')
        batch_op.alter_column('data',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
